networks:
  chatnet:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: chat-server
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks: [chatnet]

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    stdin_open: true
    tty: true
    environment:
      - HOST=server
      - PORT=5000
    depends_on: [server]
    networks: [chatnet]
